GET http://localhost:8000/users
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "PhuThuan",
    "password": "password"
}

###
POST http://localhost:8000/user/signup
Content-Type: application/json

{
    "email": "phuthuan.trannguyen@aiesec.net"
}

###
POST http://localhost:8000/user/verify-otp
Content-Type: application/json

{
    "email": "phuthuan.trannguyen@aiesec.net",
    "otp": "457849"
}
###
PUT http://localhost:8000/user/set-password-username
Content-Type: application/json

{
    "email": "phuthuan.trannguyen@aiesec.net",
    "password": "123456789",
    "username": "PhuthuanDzai"
}
###
POST http://localhost:8000/user/login
Content-Type: application/json

{
    "email": "phuthuan.trannguyen@aiesec.net",
    "password": "PhuThuan"
}

###
PUT http://localhost:8000/user/change-password
Content-Type: application/json

{
    "userID": "68f79841532b8744f537b2e3",
    "password": "Ot&fRf7n",
    "newPassword": "PhuThuan"
}
###
POST http://localhost:8000/user/google/login
Content-Type: application/json

{
    "email": "23521554@gm.uit.edu.vn",
    "password": "1596453758"
}
###
POST http://localhost:8000/user/forgot-password
Content-Type: application/json

{
    "email": "phuthuan.trannguyen@aiesec.net"
}
###
GET http://localhost:8000/user/google/login

###
DELETE http://localhost:80000/user/delete
Content-Type: application/json

{
    "userID": "68f33de9a2780fa673ba35cd",
    "password": "123456789",
}
//--------------------------PRODUCT--------------------
###
POST http://localhost:8000/menu/add
Content-Type: application/json

{
    "name": "Strawberries Cheese",
    "productID": "C04", 
    "price": "100000", 
    "category": "cake",
    "picture": "https://res.cloudinary.com/dmjq5dtyz/image/upload/cld-sample",
    "description": "This dessert features a buttery biscuit base topped with a silky smooth cream cheese layer. Fresh strawberry sauce adds a fruity sweetness, creating a perfect balance of tangy and creamy in every bite."
}
###
DELETE  http://localhost:8000/menu/delete
Content-Type: application/json

{
    "productID": "A01"
}

###
GET http://localhost:8000/menu/all-product

###
GET http://localhost:8000/menu/product?productID=E01

###
GET http://localhost:8000/menu/filter?category=cake

###
DELETE http://localhost:8000/menu/favorite-delete?userID=68f34f6e3861439314517ab2&productID=B01

### 
GET http://localhost:8000/menu/favorite-list?userID=68f34f6e3861439314517ab2

###
POST http://localhost:8000/menu/favorite-add?userID=68f34f6e3861439314517ab2&productID=B01 

###
POST http://localhost:8000/cart/add
Content-Type: application/json

{
    "userID": "68f34f6e3861439314517ab2",
    "productID": "A02"
}

###
PUT http://localhost:8000/cart/update-decrease?userID=68f34f6e3861439314517ab2&productID=A03

###
DELETE http://localhost:8000/cart/delete-all?userID=68f34f6e3861439314517ab2

###
GET http://localhost:8000/cart/view-and-caculate-total-money?userID=68f34f6e3861439314517ab2

###
POST http://localhost:8000/order/create
Content-Type: application/json

{
    "userID": "68f79841532b8744f537b2e3",
    "paymentMethod": "momo",
    "paymentStatus": "not_done",
    "deliver": "false",
    "deliverAddress": "123 Nguyễn Văn Cừ, Q5",
    "note": "Giao trong giờ hành chính"
}
###
PUT http://localhost:8000/order/change-order-status?orderID=ORD-1760863513250&status=done
###
GET http://localhost:8000/order/view-all

###
GET http://localhost:8000/order/list?startDate=2025-10-19&endDate=2025-10-19

###
GET http://localhost:8000/payment/confirm?orderID=ORD-1761275648168
###
POST http://localhost:8000/order/review-order-and-products?orderID=ORD-1760863513250
Content-Type: application/json

{
  "orderReview": "Đơn hàng giao nhanh, nhân viên thân thiện.",
  "productsReview": [
    { "productID": "A03", "rating": 5, "comment": "Rất ngon!" },
    { "productID": "B01", "rating": 4, "comment": "Ổn, giá hợp lý" },
    { "productID": "A02", "rating": 5, "comment": "Ổn, giá hợp lý" }
  ]
}

###
PUT http://localhost:8000/order/change-order-review?orderID=ORD-1760863513250
{
  "orderReview": "Siêu nhân hồng",
  "productsReview": [
    { "productID": "A03", "rating": 5, "comment": "Rất ngon!" },
    { "productID": "B01", "rating": 4, "comment": "Ngon nhưng mà giá chát quá nha" },
  ]
}
###
POST http://localhost:8000/payment-momo/create-payment-momo
Content-Type: application/json

{
    "orderID": "ORD-1761275648168",
    "userID": "68f79841532b8744f537b2e3"
}
###
GET http://localhost:8000/payment-momo/confirm?orderID=ORD-1762821679885
###
POST http://localhost:8000/payment-momo/create-payment-momo
Content-Type: application/json

{
    "orderID": "ORD-1762739684875"
}
###
POST http://13.250.179.85/payment-momo/create-payment-momo
Content-Type: application/json

{
    "orderID": "ORD-1762739684875"
}


###
POST http://localhost:8000/topping/add 
Content-Type: application/json

{
    "name": "Trân châu đen",
    "toppingID": "T01",
    "price": 10000,
    "out_of_service": false
}


###
POST http://localhost:8000/cart/add
Content-Type: application/json

{
    "userID": "68f79841532b8744f537b2e3", 
    "productID": "C04", 
    "quantity": 2, 
    "size": "large",
    "topping": ["Trân châu trắng"], 
    "note": "Nhớ làm nóng cho tôi nhé!"
}
###
PUT http://localhost:8000/cart/update-decrease 
Content-Type: application/json

{
    "userID": "68f79841532b8744f537b2e3",
    "itemID": "68f89201a88caad868584a06"
}

###
DELETE http://localhost:8000/cart/delete  
Content-Type: application/json

{
    "userID": "68f79841532b8744f537b2e3",
    "itemID": "68f8904a799430e170879fb2"
}
### 
GET http://localhost:8000/cart/view-and-caculate-total-money?userID=68f79841532b8744f537b2e3

### 
POST http://localhost:8000/voucher/create
Content-Type: application/json

{
    "description": "Tôi bị khùng",
    "discountType": "percentage",
    "discountValue": "10",
    "minPurchaseAmount": "200000",  
    "validFrom": "2025-01-01T00:00:00.000Z",
    "validTo": "2025-12-31T23:59:59.000Z",
    "usageLimit": "1",
    "applicableProducts": null
}