POST http://localhost:8000/order/create
Content-Type: application/json

{
    "userID": "68f79841532b8744f537b2e3"
}
###
DELETE http://localhost:8000/order/delete-interrupt-order
Content-Type: application/json

{
    "userID": "68f79841532b8744f537b2e3"
}
###
GET http://localhost:8000/address/suggestion?input=39/37 Hoàng Bật Đạt, Tân Bình 

###
POST http://localhost:8000/address/add 
Content-Type: application/json

{
    "name": "Phu Thuan", 
    "userID": "68f79841532b8744f537b2e3", 
    "address": "Hoàng Bật Đạt, Phường 15, 72100, Tân Bình, Thành phố Hồ Chí Minh, Việt Nam", 
    "phone": "0812930689", 
    "type": "home"
}

###
POST http://localhost:8000/deliver/calculate-fee
Content-Type: application/json

{
    "orderID": "ORD-1765021368328", 
    "userID": "68f79841532b8744f537b2e3", 
    "tipsforDriver": 5000, 
    "addressID": "ADDR-1765022289961"
}
###
POST https://76187f00e220.ngrok-free.app/momo/create
Content-Type: application/json

{
    "orderID": "ORD-1765021368328"
}

###
POST https://76187f00e220.ngrok-free.app/notification/send-all
Content-Type: application/json

{
    "notificationID": "NOTI-1765024594116", 
    "scheduleAt": null
}

###
POST http://localhost:8000/notification/create 
Content-Type: application/json

{
    "title": "Test nha mom", 
    "message": "Gobi không im lặng là cook liền", 
    "scheduleAt": null
}

###
GET http://localhost:8001/api/v1/recommend/44905
###
GET http://localhost:8001/api/v1/recommend/also_viewed/75762?exclude_items=D6

###
GET http://localhost:8000/recommend/all-user

###
POST https://38d670f12a80.ngrok-free.app/momo/create
Content-Type: application/json

{
    "orderID": "ORD-1765118833369-820"
}
